name: Publish package
on:
  release:
    types: [created]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup npmrc
        run: |
          echo "@sky-mavis:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish @sky-mavis/katana-core
        run: cd packages/katana-core && npm publish --access=public
        if: ${{ true == startsWith(github.event.release.tag_name, 'katana-core') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @sky-mavis/smart-order-router
        run: cd packages/smart-order-router && npm publish --access=public
        if: ${{ true == startsWith(github.event.release.tag_name, 'smart-order-router') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @sky-mavis/katana-swap
        run: cd packages/katana-swap && npm publish --access=public
        if: ${{ true == startsWith(github.event.release.tag_name, 'katana-swap') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Publish @sky-mavis/katana-swap
        run: cd packages/katana-swap && npm publish --access=public --tag alpha
        if: ${{ true == startsWith(github.event.release.tag_name, 'katana-swap-alpha') }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
